# Generated by Django 5.2.4 on 2025-10-18 11:01

import promotion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='website',
            field=models.CharField(max_length=255, validators=[promotion.validators.DomainValidator()]),
        ),
    ]

