# Generated by Django 5.2.4 on 2025-10-18 11:08

import promotion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotion_name_alter_promotion_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='website',
            field=models.CharField(max_length=100, validators=[promotion.validators.DomainValidator()]),
        ),
    ]

