# Generated by Django 5.2.4 on 2025-10-18 14:27

import promotion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_alter_promotion_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='website',
            field=models.CharField(max_length=50, validators=[promotion.validators.DomainValidator()]),
        ),
    ]

