# Generated by Django 5.2.4 on 2026-04-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_alter_promotion_name_alter_promotion_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionimage',
            name='usage',
            field=models.CharField(choices=[('top', 'Top image'), ('popup_bg', 'Popup background')], db_index=True, default='top', max_length=20),
        ),
    ]

