# Generated by Django 5.2.4 on 2026-04-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_promotionimage_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='theme',
            field=models.JSONField(default={'background_image': {'path': '', 'style': ''}, 'bottom_image': {'path': '', 'style': ''}, 'countdown': {'active': True, 'colors': {'background': '#cee8e8', 'text': '#2C7A7B'}, 'valid_time': '15'}, 'gameColors': {}, 'gameID': 1, 'image': {'path': '', 'style': ''}, 'input_fields': [{'id': 'default_email_field', 'label': 'Email', 'name': 'email', 'placeholder': 'Enter your email address', 'required': True, 'style': {'alignment': 'center', 'background': '#ffffff', 'border-color': '#dee2e6', 'border-radius': '12', 'border-width': '1', 'color': '#000000', 'height': '40', 'padding': '12', 'placeholder-color': '#6c757d', 'width': '100'}, 'type': 'email'}, {'action': 'submit_form', 'action_url': '', 'id': 'default_submit_btn', 'label': 'Submit Button', 'name': 'submit_button', 'style': {'border': 'none', 'border-radius': '30px', 'box-shadow': 'inset 1px 1px rgba(255, 255, 255, 0.1), 2px 2px 1px 1px rgba(0, 0, 0, 0.1)', 'font-family': 'Arial', 'font-size': '16px', 'font-style': 'normal', 'font-weight': 'bold', 'height': '40px', 'letter-spacing': '0.05em', 'text-align': 'center', 'text-decoration': 'none', 'width': '100%'}, 'text': 'Try your luck', 'type': 'submit_button'}, {'action': 'close_form', 'action_url': '', 'id': 'default_close_btn', 'label': 'Button', 'name': 'button_default_close', 'style': {'color': '#f2f2f2', 'font-family': 'Arial', 'font-size': '14px', 'font-style': 'normal', 'font-weight': 'normal', 'text-align': 'center', 'text-decoration': 'none'}, 'text': "No, I don't feel lucky", 'type': 'submit_button'}], 'options': {'prevent_dublicate': True, 'property_id': '', 'show_on_mobile': True, 'smart_reward': False, 'specific_items': '', 'specific_urls': '', 'start_delay': '10', 'start_delay_active': False, 'trigger_intent_leave': False, 'trigger_scroll_down': False}, 'popup_settings': {'font_family': '', 'popup_opening_effect': 'fade_in_scale', 'popup_opening_effect_duration': 700, 'popup_position': 'left', 'popup_position_grid': 'middle_center', 'popup_size': 'medium'}, 'popup_type': 'gaming', 'template': 101, 'texts': {'description': 'You have a chance to win a nice big fat discount. Are you feeling lucky? Give it a spin!', 'disclaimer': 'You can spin the wheel only once. If you win, coupon can be claimed for 15 minutes only. Same email must be used when ordering.', 'headline': "Our store's special bonus unlocked!"}}),
        ),
    ]

