# Generated by Django 5.2.4 on 2025-11-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpTopic',
        ),
    ]
